### ISSUE TITLE
'Florence2ForConditionalGeneration' object has no attribute '_supports_sdpa'

### ISSUE THREAD

**Issue by d11dmb** [miaoshouai/ComfyUI-Miaoshouai-Tagger#61]
<img width="667" height="401" alt="Image" src="https://github.com/user-attachments/assets/2544c421-ebbb-49c5-9850-463b84830075" />

Any help guys?

**Comment by chenav** [comment]
you have to force transformers to version 4.51.2, not above (it does not work with 4.55.0, current last version).
To do so, pay attention to the requirements.txt in both Comfyui folder but also Comfyui-Manager (which overrides it, as it is executed in a second step).

transformers==4.51.2
